Upgrade textual to 5.0.1
Tree-sitter had a breaking change in version 25.0.0. As a result, Tygenie
crashes when adding a new note with the following error:

```
AttributeError: 'tree_sitter.Query' object has no attribute 'captures'
```

Textual released a fix[1] for this. Let's use it.

[1] https://github.com/Textualize/textual/issues/5976